spring.application.name=mcp-server
spring.ai.mcp.server.name=mcp-server
spring.ai.mcp.server.version=0.0.1

# these 2 lines are necessary, otherwise we get an error when Claude uses the MCP server
spring.main.banner-mode=off
logging.threshold.console=off

#spring.main.web-application-type=none
spring.ai.mcp.server.protocol=STREAMABLE



sncf.api.base-url=https://api.sncf.com/v1/coverage/sncf/
sncf.api.token=0c06483a-a23f-464a-92f1-106300d63a3c

#permet de lancé le serveur en streamable HTTP
logging.file.name=./model-context-protocol/weather/starter-webflux-server/target/starter-webflux-server.log

